<?php declare(strict_types=1);
//> This file is part of Webkernel.
//> (c) 2025 - 2027 Numerimondes, El Moumen Yassine
//> Yassine El Moumen <yassine@numerimondes.com> | <platform@webkernelphp.com>
//> For the full copyright and license information, please view the LICENSE
//> file that was distributed with this source code.

namespace Webkernel\Console\Commands\DumpAutoloadCommand;

use Webkernel\Typography\TypographySystem;

trait CanDumpTypography
{
    /**
     * Write WTS rules + self-hosted fonts under webapp_path("public/$typo_path").
     *
     * @return void
     */
    private function dump_typography(): void
    {
        $dir = TypographySystem::path(TypographySystem::DIR);
        if (! \is_dir($dir) && ! \mkdir($dir, 0775, true) && ! \is_dir($dir)) {
            $this->terminal()->warning('cannot create '.$dir);

            return;
        }
        $this->write_typography_rules();
        $this->assemble_typography_fonts();
    }

    /**
     * @return void
     */
    private function write_typography_rules(): void
    {
        $source = $this->codebase_root().'/resources/css/wts.css';
        $dest = TypographySystem::path(TypographySystem::RULES_CSS);
        if (! \is_file($source)) {
            $this->terminal()->warning('missing '.$source);

            return;
        }
        $css = \file_get_contents($source);
        if (! \is_string($css)) {
            return;
        }
        \file_put_contents($dest, $css, \LOCK_EX);
    }

    /**
     * Rebuild aggregate font CSS from family.css already on disk.
     *
     * //> Dump does not download woff2. Google CDN until those files exist.
     *
     * @return void
     */
    private function assemble_typography_fonts(): void
    {
        $dir = TypographySystem::path(TypographySystem::DIR);
        $chunks = [];
        foreach (\array_keys(TypographySystem::catalog()) as $slug) {
            $family_css = $dir.DIRECTORY_SEPARATOR.$slug.DIRECTORY_SEPARATOR.'family.css';
            if (! \is_file($family_css)) {
                continue;
            }
            $chunk = \file_get_contents($family_css);
            if (\is_string($chunk) && $chunk !== '') {
                $chunks[] = $chunk;
            }
        }
        if ($chunks === []) {
            return;
        }
        \file_put_contents(
            TypographySystem::path(TypographySystem::FONTS_CSS),
            "/* Webkernel Typography System — generated by dump-autoload */\n\n".\implode("\n", $chunks),
            \LOCK_EX,
        );
    }
}
