<?php declare(strict_types=1);

//> This file is part of Webkernel.
//> (c) 2025 - 2027 Numerimondes, El Moumen Yassine
//> Yassine El Moumen <yassine@numerimondes.com> | <platform@webkernelphp.com>
//> For the full copyright and license information, please view the LICENSE
//> file that was distributed with this source code.
//
//> Compiled artifact. Do not edit.
//> Generated by: CompilationStore
return [
    'app' => [
        'debug' => false,
        'env' => 'prod',
    ],
    'database' => [
        'driver' => 'mysql',
        'host' => '127.0.0.1',
        'port' => 3306,
        'database' => 'webkernel',
        'username' => 'root',
        'password' => '',
    ],
    'cache' => [
        'driver' => 'apcu',
        'fallback' => 'redis',
    ],
    'logging' => [
        'level' => 'warning',
    ],
    'blog.posts_per_page' => 20,
    'blog.cache_ttl' => 300,
];
