<?php declare(strict_types=1);

//> This file is part of Webkernel.
//> (c) 2025 - 2027 Numerimondes, El Moumen Yassine
//> Yassine El Moumen <yassine@numerimondes.com> | <platform@webkernelphp.com>
//> For the full copyright and license information, please view the LICENSE
//> file that was distributed with this source code.
//
//> Compiled artifact. Do not edit.
//> Generated by: CompilationStore
return [
    'dirs' => [
        '/home/yassine/Projects/framework/refactor/x-webkernel/codebase/src/View/views',
    ],
    'namespaces' => [
        '' => [
            '/home/yassine/Projects/framework/refactor/x-webkernel/codebase/src/View/views',
        ],
        'webkernel' => [
            '/home/yassine/Projects/framework/refactor/x-webkernel/codebase/src/View/views',
        ],
    ],
    'components' => [
        'webkernel' => [
            '/home/yassine/Projects/framework/refactor/x-webkernel/codebase/src/View/views/components',
        ],
    ],
];
