<?php declare(strict_types=1);

namespace Webkernel\Lifecycle\Vite\Generator;

use Webkernel\Lifecycle\Vite\Support\LaravelViteEntries;

/**
 * Renders vite.webapp.ts — thin surface: resolve entries, cache anchors, @source.
 */
final class Template
{
    private const COPYRIGHT_START_YEAR = 2025;

    public static function render(string $json_payload, string $generated_at, string $cli_prefix): string
    {
        $end_year = ((int) date('Y')) + 1;
        $copyright = sprintf(
            '// (c) %d - %d Numerimondes, El Moumen Yassine',
            self::COPYRIGHT_START_YEAR,
            $end_year,
        );

        $body = <<<'TS'
// This file is part of Webkernel.
__COPYRIGHT__
//
// AUTO-GENERATED by webkernel/lifecycle
// on __GENERATED_AT__ — do not edit.
//
// @vite(['resources/css/app.css', 'resources/js/app.js']) works with host files
// or build-time anchors under storage/framework/cache/webkernel/vite/.

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  realpathSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import type { Plugin } from "vite";

export type ViteWebappModule = {
  root: string;
  config_file: string | null;
  has_config: boolean;
  name?: string;
};

export type ViteWebapp = {
  generated_at: string;
  // Composer config.vendor-dir (vendor | third_party | custom).
  vendor_dir: string;
  module_dirs: string[];
  extensions: string;
  extra_globs: string[];
  entries: string[];
  aliases: Record<string, string>;
  tailwind_sources: string[];
  tailwind_globs: string[];
  // npm package.json workspaces globs — Composer install layout only:
  //   {vendor_dir}/org/name  (e.g. third_party/webkernel/codebase)
  //   modules/org/name
  // Never path-repo sources (software). Synced into host package.json on generate.
  packages_json_globs: string[];
  // Package stylesheets folded into host app.css (single CSS bundle).
  css_imports: string[];
  modules: ViteWebappModule[];
};

export const LARAVEL_ENTRIES = __LARAVEL_ENTRIES__ as const;
export const VITE_CACHE = __VITE_CACHE__;

const webapp = __WEBAPP_JSON__ as const satisfies ViteWebapp;
export default webapp;

const posix = (p: string) => p.split(sep).join("/");

function anchor(root: string, entry: string): string {
  const user = join(root, entry);
  if (existsSync(user)) return user;

  const cached = join(root, VITE_CACHE, entry);
  mkdirSync(dirname(cached), { recursive: true });
  writeFileSync(
    cached,
    entry.endsWith(".css")
      ? // source(none): only explicit @source globs (webapp_plugin injects them).
        // Without this, Tailwind auto-scan skips .gitignore paths (third_party/, modules/).
        '/* webkernel cache anchor */\n@import "tailwindcss" source(none);\n'
      : "/* webkernel cache anchor */\n",
  );
  return cached;
}

export function resolve_entries(root: string = process.cwd()): string[] {
  const out: string[] = [];

  for (const entry of webapp.entries) {
    if (posix(entry).includes(VITE_CACHE)) continue;
    if (existsSync(join(root, entry))) out.push(entry);
    else console.warn(`[__CLI__] skip missing entry: ${entry}`);
  }

  for (const entry of LARAVEL_ENTRIES) {
    anchor(root, entry);
    if (!out.includes(entry)) out.push(entry);
  }

  console.info(`\n[__CLI__] vite entries: ${out.join(", ")}\n`);
  return out;
}

// npm workspaces globs from the snapshot (same as host package.json workspaces).
// Webkernel-only: {vendor}/webkernel/*, modules/*/* , software/* — not all of vendor.
export function packages_json_globs(): string[] {
  const fromSnap = (webapp as ViteWebapp).packages_json_globs;
  if (Array.isArray(fromSnap) && fromSnap.length > 0) {
    return [...fromSnap];
  }
  const v = (webapp.vendor_dir || "vendor").replace(/^\/+|\/+$/g, "");
  return [`${v}/webkernel/*`, "modules/*/*", "software/*"];
}

// Expand one workspace glob to package roots that contain package.json.
// Supports patterns: prefix/*, prefix/*/* (prefix may be multi-segment).
function expand_package_glob(root: string, glob: string, consider: (rel: string) => void): void {
  const g = glob.replace(/\\/g, "/").replace(/^\/+|\/+$/g, "");

  // prefix/*/*
  const double = g.match(/^(.*)\/\*\/\*$/);
  if (double) {
    const baseRel = double[1];
    const base = join(root, baseRel);
    if (!existsSync(base)) return;
    try {
      for (const org of readdirSync(base)) {
        if (org.startsWith(".")) continue;
        const orgDir = join(base, org);
        try {
          for (const pkg of readdirSync(orgDir)) {
            if (pkg.startsWith(".")) continue;
            consider(posix(join(baseRel, org, pkg)));
          }
        } catch {
          // not a dir
        }
      }
    } catch {
      // ignore
    }
    return;
  }

  // prefix/*  (prefix may be multi-segment, e.g. third_party/webkernel)
  const single = g.match(/^(.*)\/\*$/);
  if (single) {
    const baseRel = single[1];
    const base = join(root, baseRel);
    if (!existsSync(base)) return;
    try {
      for (const name of readdirSync(base)) {
        if (name.startsWith(".")) continue;
        consider(posix(join(baseRel, name)));
      }
    } catch {
      // ignore
    }
  }
}

// Reliable discovery:
// 1) Composer Webkernel packages from webapp.modules (truth)
// 2) packages_json_globs (vendor/webkernel, modules, software)
// Only dirs with package.json are npm workspaces. Realpath-deduped.
// Returns project-relative paths.
export function resolve_workspace_packages(root: string = process.cwd()): string[] {
  const seen = new Map<string, string>();

  const consider = (rel: string) => {
    const abs = join(root, rel);
    if (!existsSync(join(abs, "package.json"))) return;
    let real = abs;
    try {
      real = realpathSync(abs);
    } catch {
      // keep abs
    }
    if (!seen.has(real)) {
      seen.set(real, posix(rel));
    }
  };

  // 1) Snapshot modules = Composer-installed Webkernel packages (path or vendor).
  const modules = (webapp as ViteWebapp).modules ?? [];
  const composerRoots: string[] = [];
  for (const mod of modules) {
    if (!mod?.root) continue;
    const rel = posix(String(mod.root));
    composerRoots.push(rel + (mod.name ? ` (${mod.name})` : ""));
    consider(rel);
  }

  // 2) Workspace globs (webkernel vendor + modules + software monorepo).
  for (const glob of packages_json_globs()) {
    expand_package_glob(root, glob, consider);
  }

  const list = [...seen.values()].sort();
  console.info(
    `[__CLI__] packages_json_globs: ${packages_json_globs().join(", ")}`,
  );
  console.info(
    `[__CLI__] composer webkernel packages: ${composerRoots.length ? composerRoots.join(", ") : "(none)"}`,
  );
  console.info(
    `[__CLI__] npm workspace packages (runtime, have package.json): ${list.length ? list.join(", ") : "(none)"}`,
  );
  const missingPkgJson = modules
    .filter((m) => m?.root && !existsSync(join(root, String(m.root), "package.json")))
    .map((m) => posix(String(m.root)) + (m.name ? ` (${m.name})` : ""));
  if (missingPkgJson.length) {
    console.info(
      `[__CLI__] webkernel packages without package.json (add one to join npm workspaces): ${missingPkgJson.join(", ")}`,
    );
  }
  return list;
}

function source_block(root: string): string {
  const base = posix(root);
  // Absolute paths so Tailwind resolves monorepo trees even when the physical
  // app.css lives under storage/framework/cache/webkernel/vite/…
  const seen = new Set<string>();
  const lines: string[] = [];
  for (const g of webapp.tailwind_globs) {
    const abs = g.startsWith("/") ? g : `${base}/${g}`;
    if (seen.has(abs)) continue;
    seen.add(abs);
    lines.push(`@source "${abs}";`);
  }
  return lines.join("\n");
}

// Import package CSS into host app.css (onboarding, imagery, site chrome).
// Paths are relative to the physical app.css file so Vite can resolve them.
function css_import_block(root: string, from_css_file: string): string {
  const base = posix(root);
  const from_dir = dirname(from_css_file);
  const imports = (webapp as ViteWebapp).css_imports ?? [];
  const seen = new Set<string>();
  const lines: string[] = [];
  for (const rel of imports) {
    if (!rel || typeof rel !== "string") continue;
    const abs = rel.startsWith("/") ? rel : join(base, rel);
    if (seen.has(abs) || !existsSync(abs)) continue;
    seen.add(abs);
    let rel_to = posix(relative(from_dir, abs));
    if (!rel_to.startsWith(".")) {
      rel_to = "./" + rel_to;
    }
    lines.push(`@import "${rel_to}";`);
  }
  return lines.join("\n");
}

function fix_manifest(root: string): void {
  const path = join(root, "public/build/manifest.json");
  if (!existsSync(path)) return;

  const manifest = JSON.parse(readFileSync(path, "utf8")) as Record<
    string,
    Record<string, unknown>
  >;
  let dirty = false;

  for (const entry of LARAVEL_ENTRIES) {
    const abs = posix(anchor(root, entry));
    const rel = posix(join(VITE_CACHE, entry));
    let chunk = manifest[entry];

    for (const key of Object.keys(manifest)) {
      if (key === entry) continue;
      if (
        key === abs
        || key === rel
        || (key.includes(VITE_CACHE) && key.endsWith("/" + entry))
      ) {
        chunk ??= manifest[key];
        delete manifest[key];
        dirty = true;
      }
    }

    if (chunk) {
      manifest[entry] = { ...chunk, src: entry };
      dirty = true;
    }
  }

  if (dirty) writeFileSync(path, JSON.stringify(manifest, null, 2) + "\n");
}

export function webapp_plugin(root: string = process.cwd()): Plugin {
  const sources = source_block(root);
  const aliases: Record<string, string> = {};

  for (const [a, t] of Object.entries(webapp.aliases) as [string, string][]) {
    aliases[a] = join(root, t);
  }
  for (const entry of LARAVEL_ENTRIES) {
    aliases[entry] = anchor(root, entry);
  }

  return {
    name: "webkernel-vite-webapp",
    enforce: "pre",
    resolveId(id) {
      for (const entry of LARAVEL_ENTRIES) {
        if (id === entry || posix(id).endsWith("/" + entry)) {
          return anchor(root, entry);
        }
      }
      return null;
    },
    config: () => ({
      resolve: { alias: aliases },
    }),
    transform(code, id) {
      // Only host app.css is the Tailwind + package-CSS bundle.
      if (!id.includes(".css") || id.includes("node_modules")) return null;

      const isAppCss =
        posix(id).endsWith("/resources/css/app.css")
        || (posix(id).includes(VITE_CACHE) && posix(id).endsWith("app.css"));

      if (!isAppCss) return null;
      if (!/@import\s+["']tailwindcss["']/.test(code)) return null;

      const packageCss = css_import_block(root, id);

      let next = code
        .replace(/@source\s+[^;]+;/g, "")
        // Drop previous package imports we may have injected (idempotent HMR).
        .replace(/@import\s+"(\.\.\/)+software[^"]+";\n?/g, "")
        .replace(/@import\s+"(\.\.\/)+software-modules[^"]+";\n?/g, "");

      next = next.replace(
        /@import\s+["']tailwindcss["'](?:\s+source\([^)]*\))?;/,
        '@import "tailwindcss" source(none);',
      );

      // CSS: @import first, then Tailwind @source.
      const after = [packageCss, sources].filter(Boolean).join("\n\n");
      next = next.replace(
        /@import\s+["']tailwindcss["']\s+source\(none\);/,
        (m) => (after !== "" ? `${m}\n\n${after}` : m),
      );

      return next === code ? null : { code: next, map: null };
    },
    closeBundle: () => fix_manifest(root),
  };
}

export async function load_webapp(): Promise<ViteWebapp> {
  return webapp;
}
TS;

        return str_replace(
            [
                '__COPYRIGHT__',
                '__GENERATED_AT__',
                '__WEBAPP_JSON__',
                '__CLI__',
                '__LARAVEL_ENTRIES__',
                '__VITE_CACHE__',
            ],
            [
                $copyright,
                $generated_at,
                $json_payload,
                $cli_prefix,
                json_encode(LaravelViteEntries::LOGICAL, JSON_THROW_ON_ERROR),
                json_encode(LaravelViteEntries::CACHE_REL, JSON_THROW_ON_ERROR),
            ],
            $body
        );
    }
}
