<?php declare(strict_types=1);
//> Auto-generated by webkernel/lifecycle — do not edit.
//> Re-generated on every `composer dump-autoload`.

if (! function_exists('base_path')) {
    function base_path(string $path = ''): string
    {
        $base = '/home/yassine/Projects/framework/refactor/internal/dependencies';
        return $path !== '' ? $base . DIRECTORY_SEPARATOR . ltrim($path, '/\\') : $base;
    }
}

if (! function_exists('platform_path')) {
    function platform_path(string $path = ''): string
    {
        return base_path($path);
    }
}

if (! function_exists('storage_path')) {
    function storage_path(string $path = ''): string
    {
        $storage = base_path('storage');
        return $path !== '' ? $storage . DIRECTORY_SEPARATOR . ltrim($path, '/\\') : $storage;
    }
}