<?php declare(strict_types=1);
//> Auto-generated by webkernel/lifecycle — do not edit.
//> Re-generated on every `composer dump-autoload`.

if (! function_exists('vendor_path')) {
    function vendor_path(string $path = ''): string
    {
        $vendor = '/home/yassine/Projects/framework/refactor/internal/dependencies/packagist';
        return $path !== '' ? $vendor . DIRECTORY_SEPARATOR . ltrim($path, '/\\') : $vendor;
    }
}

if (! function_exists('autoload_path')) {
    function autoload_path(): string
    {
        return vendor_path('autoload.php');
    }
}