<?php declare(strict_types=1);
//> This file is part of Webkernel.
//> (c) 2025 - 2027 Numerimondes, El Moumen Yassine
//> Yassine El Moumen <yassine@numerimondes.com> | <platform@webkernelphp.com>
//> For the full copyright and license information, please view the LICENSE
//> file that was distributed with this source code.

return [
	'schema_version' => '1.0.1',

	'id'        => 'bf0b7a6fe1dc0f33e62c091b9c7fe6e9',
	'hostname'  => gethostname(),
	'ip'        => gethostbyname(\gethostname()),
	'uuid'      => Instance::machine_uuid(),
	'macs'      => Instance::macs(),
	'path'      => Instance::filepath(),
	'created'   => date('c'), // ISO timestamp

	'autoload'  => 'platform/dependencies/packagist/autoload.php', // Generated by platform/bootstrap/fast-boot.php. Do not edit.

	'platform' => [
		'id'             => 'bf0b7a6fe1dc0f33e62c091b9c7fe6e9',
		'path'           => 'platform',
		'config_path'    => __DIR__,
		'bootstrap_path' => 'platform/bootstrap',
		'cache_path'	 => 'platform/cache',
		'settings_path'  => 'platform/settings',
		'storage_path'   => 'platform/storage',
		'telemetry_path' => 'platform/telemetry',
		'temporary_path' => 'platform/temporary',
	],

	'dependencies' => [
		'path'              => 'platform/dependencies',
		'packagist_path'    => 'platform/dependencies/packagist',
		'node_modules_path' => 'platform/dependencies/node_modules',
		'package_json'      => 'platform/dependencies/package.json',
	],

	'modules' => [
		'path'          => 'modules',
		'manifest_path' => 'platform/cache/modules_manifest.php',
	],

	'public' => [
		'path'  => 'public',
		'index' => 'public/index.php',
	],

	'js' => [
		'manager'           => 'npm',
		'package_json'      => 'platform/dependencies/package.json',
		'node_modules_path' => 'platform/dependencies/node_modules',
	],
];
