<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname(dirname($vendorDir)));

return array(
    'Webkernel\\View\\' => array($vendorDir . '/webkernel/view/src'),
    'Webkernel\\Typography\\' => array($vendorDir . '/webkernel/typography/src'),
    'Webkernel\\Route\\' => array($vendorDir . '/webkernel/route/src'),
    'Webkernel\\Request\\' => array($vendorDir . '/webkernel/request/src'),
    'Webkernel\\Platform\\' => array($vendorDir . '/webkernel/platform/src'),
    'Webkernel\\Performance\\' => array($vendorDir . '/webkernel/performance/src/Performance'),
    'Webkernel\\Paths\\' => array($vendorDir . '/webkernel/paths/src'),
    'Webkernel\\Liveview\\' => array($vendorDir . '/webkernel/liveview/src'),
    'Webkernel\\Lifecycle\\' => array($vendorDir . '/webkernel/lifecycle/src'),
    'Webkernel\\Instance\\' => array($vendorDir . '/webkernel/instance/src'),
    'Webkernel\\DevTools\\' => array($vendorDir . '/webkernel/devtools/src'),
    'Webkernel\\Console\\' => array($vendorDir . '/webkernel/console/src'),
    'Webkernel\\Config\\' => array($vendorDir . '/webkernel/config/src'),
    'Webkernel\\Composables\\' => array($vendorDir . '/webkernel/composables/src'),
    'Webkernel\\Component\\' => array($vendorDir . '/webkernel/component/src'),
    'Webkernel\\Communication\\' => array($vendorDir . '/webkernel/communication/src'),
    'Webkernel\\Commands\\' => array($vendorDir . '/webkernel/commands/src'),
    'Webkernel\\' => array($vendorDir . '/webkernel/codebase/src', $vendorDir . '/webkernel/platform-provider/src'),
    'Psr\\SimpleCache\\' => array($vendorDir . '/psr/simple-cache/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/src'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
    'Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'Psr\\Clock\\' => array($vendorDir . '/psr/clock/src'),
    'Psr\\Cache\\' => array($vendorDir . '/psr/cache/src'),
    'PhpParser\\' => array($vendorDir . '/nikic/php-parser/lib/PhpParser'),
    'PHPMailer\\PHPMailer\\' => array($vendorDir . '/phpmailer/phpmailer/src'),
    'DeepCopy\\' => array($vendorDir . '/myclabs/deep-copy/src/DeepCopy'),
    'Composer\\Installers\\' => array($vendorDir . '/composer/installers/src/Composer/Installers'),
);
