<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname(dirname($vendorDir)));

return array(
    '23018b0a9c1a1e28e4fd8e8d1787d9a8' => $vendorDir . '/webkernel/lifecycle/load.lifecycle.functions.php',
    'a7e1958e8ac4599b4fc92e46f8f9c705' => $vendorDir . '/webkernel/config/load.config.function.php',
    '6124b4c8570aa390c21fafd04a26c69f' => $vendorDir . '/myclabs/deep-copy/src/DeepCopy/deep_copy.php',
    'b3937b7fa35431fe0895577483870c74' => $vendorDir . '/webkernel/codebase/namespacer.php',
    'ec07570ca5a812141189b1fa81503674' => $vendorDir . '/phpunit/phpunit/src/Framework/Assert/Functions.php',
);
