<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname(dirname($vendorDir)));

return array(
    '23018b0a9c1a1e28e4fd8e8d1787d9a8' => $vendorDir . '/webkernel/lifecycle/load.lifecycle.functions.php',
    'a7e1958e8ac4599b4fc92e46f8f9c705' => $vendorDir . '/webkernel/config/load.config.function.php',
    'b7c9a164547a76f1de55ce0728ed2fb3' => $vendorDir . '/webkernel/config/load.cfg.function.php',
    'b3937b7fa35431fe0895577483870c74' => $vendorDir . '/webkernel/codebase/namespacer.php',
);
