<?php return array(
    'root' => array(
        'name' => 'webkernel/webkernel',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '6d64e5d27e2969c8617b4928af57d1f794f6393b',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'composer/installers' => array(
            'pretty_version' => 'v2.3.0',
            'version' => '2.3.0.0',
            'reference' => '12fb2dfe5e16183de69e784a7b84046c43d97e8e',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./installers',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'myclabs/deep-copy' => array(
            'pretty_version' => '1.14.0',
            'version' => '1.14.0.0',
            'reference' => '8680aa248f8e07bc8fb43f56f0f5fc77a0c96aae',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/deep-copy',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v5.8.0',
            'version' => '5.8.0.0',
            'reference' => '044a6a392ff8ad0d61f14370a5fbbd0a0107152f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phar-io/manifest' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => '54750ef60c58e43759730615a392c31c80e23176',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/manifest',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phar-io/version' => array(
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'reference' => '4f7fd7836c6f332bb2933569e566a0d6c4cbed74',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.12.0',
            'version' => '6.12.0.0',
            'reference' => 'd1ac35d784bf9f5e61b424901d5a014967f15b12',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => '11.0.12',
            'version' => '11.0.12.0',
            'reference' => '2c1ed04922802c15e1de5d7447b4856de949cf56',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => '5.1.1',
            'version' => '5.1.1.0',
            'reference' => '2f3a64888c814fc235386b7387dd5b5ed92ad903',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-invoker' => array(
            'pretty_version' => '5.0.1',
            'version' => '5.0.1.0',
            'reference' => 'c1ca3814734c07492b3d4c5f794f4b0995333da2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-invoker',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => '4.0.1',
            'version' => '4.0.1.0',
            'reference' => '3e0404dc6b300e6bf56415467ebcb3fe4f33e964',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => '7.0.1',
            'version' => '7.0.1.0',
            'reference' => '3b415def83fbcb41f991d9ebf16ae4ad8b7837b3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => '11.5.56',
            'version' => '11.5.56.0',
            'reference' => '5f83edffa6967c3db468d48a695ec7bcb02e9256',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'psr/cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'aa5030cfa5405eccfdcb1083ce040c2cb8d253bf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/clock' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'e41a24703d4560fd0acb709162f73b8adfc3aa0d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/clock',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'c71ecc56dfe541dbd90c5360474fbc405f8d5963',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => 'bb5906edc1c324c9a05aa0873d40117941e5fa90',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '2b4765fddfe3b508ac62f829e852b1501d3f6e8a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message' => array(
            'pretty_version' => '2.0',
            'version' => '2.0.0.0',
            'reference' => '402d35bcb92c70c026d1a6a9883f06b2ead23d71',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => 'f16e1d5863e37f8d8c2a01719f5b34baa2b714d3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '764e0b3939f5ca87cb904f570ef9be2d78a07865',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sebastian/cli-parser' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => '15c5dd40dc4f38794d383bb95465193f5e0ae180',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/cli-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/code-unit' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '54391c61e4af8078e5b276ab082b6d3c54c9ad64',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/code-unit-reverse-lookup' => array(
            'pretty_version' => '4.0.1',
            'version' => '4.0.1.0',
            'reference' => '183a9b2632194febd219bb9246eee421dad8d45e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit-reverse-lookup',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/comparator' => array(
            'pretty_version' => '6.3.3',
            'version' => '6.3.3.0',
            'reference' => '2c95e1e86cb8dd41beb8d502057d1081ccc8eca9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/comparator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/complexity' => array(
            'pretty_version' => '4.0.1',
            'version' => '4.0.1.0',
            'reference' => 'ee41d384ab1906c68852636b6de493846e13e5a0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/complexity',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/diff' => array(
            'pretty_version' => '6.0.2',
            'version' => '6.0.2.0',
            'reference' => 'b4ccd857127db5d41a5b676f24b51371d76d8544',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/environment' => array(
            'pretty_version' => '7.2.1',
            'version' => '7.2.1.0',
            'reference' => 'a5c75038693ad2e8d4b6c15ba2403532647830c4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/environment',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/exporter' => array(
            'pretty_version' => '6.3.2',
            'version' => '6.3.2.0',
            'reference' => '70a298763b40b213ec087c51c739efcaa90bcd74',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/exporter',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/global-state' => array(
            'pretty_version' => '7.0.2',
            'version' => '7.0.2.0',
            'reference' => '3be331570a721f9a4b5917f4209773de17f747d7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/global-state',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/lines-of-code' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'reference' => 'd36ad0d782e5756913e42ad87cb2890f4ffe467a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/lines-of-code',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-enumerator' => array(
            'pretty_version' => '6.0.1',
            'version' => '6.0.1.0',
            'reference' => 'f5b498e631a74204185071eb41f33f38d64608aa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-enumerator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-reflector' => array(
            'pretty_version' => '4.0.1',
            'version' => '4.0.1.0',
            'reference' => '6e1a43b411b2ad34146dee7524cb13a068bb35f9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-reflector',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/recursion-context' => array(
            'pretty_version' => '6.0.3',
            'version' => '6.0.3.0',
            'reference' => 'f6458abbf32a6c8174f8f26261475dc133b3d9dc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/recursion-context',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/type' => array(
            'pretty_version' => '5.1.3',
            'version' => '5.1.3.0',
            'reference' => 'f77d2d4e78738c98d9a68d2596fe5e8fa380f449',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/type',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/version' => array(
            'pretty_version' => '5.0.2',
            'version' => '5.0.2.0',
            'reference' => 'c687e3387b99f5b03b6caa64c74b63e2936ff874',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'staabm/side-effects-detector' => array(
            'pretty_version' => '1.0.5',
            'version' => '1.0.5.0',
            'reference' => 'd8334211a140ce329c13726d4a715adbddd0a163',
            'type' => 'library',
            'install_path' => __DIR__ . '/../staabm/side-effects-detector',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'theseer/tokenizer' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'reference' => 'b7489ce515e168639d17feec34b8847c326b0b3c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../theseer/tokenizer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'webkernel/actions' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '212e890369c9e4759ccfd57ded7a6b63edbe211a',
            'type' => 'webkernel-stdlib',
            'install_path' => __DIR__ . '/../webkernel/actions',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/auth' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '65a152fd33b78e079428eaaaa1c53bb7bba86bc0',
            'type' => 'webkernel-stdlib',
            'install_path' => __DIR__ . '/../webkernel/auth',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/codebase' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => 'a90d52e7bcef35986789b95daefa0dca415652a0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webkernel/codebase',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/commands' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '5998aff23f071c917d025e38e9ef4e4855a4d026',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webkernel/commands',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/communication' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '65941384a983eab037b278e8d8074581d376d3a8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webkernel/communication',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/component' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '3375abfc38b4aab8f1f0d482fa95070b1d3f863e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webkernel/component',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/components' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '8c22ba944e4e6c26011225e9860e1e30c45b0c18',
            'type' => 'webkernel-component',
            'install_path' => __DIR__ . '/../webkernel/components',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/composables' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '5d9d9f0cf6553e24798aeaeda403da975ee4c6a5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webkernel/composables',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/config' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '8da19ca99edb61ed9d2118b2f59aae6b2f802445',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webkernel/config',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/console' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '1eb57211abe5be4bbfaf9b6e469687d423353421',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webkernel/console',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/database' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '7f7e30f4a880820445392ba9be739f7b0673a321',
            'type' => 'webkernel-stdlib',
            'install_path' => __DIR__ . '/../webkernel/database',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/devtools' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '6d2ce1ff0612da40a569ae5c15314393f376cea9',
            'type' => 'webkernel-devtool',
            'install_path' => __DIR__ . '/../webkernel/devtools',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'webkernel/errors' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => 'd618b575172dcf3f3cf6cfb804fd74671c34ab81',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webkernel/errors',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/forms' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => 'b44a47bfa6a2ea4171ec488f23ec5a9b031290c5',
            'type' => 'webkernel-stdlib',
            'install_path' => __DIR__ . '/../webkernel/forms',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/http' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => 'b7d676f48228e3d4b3bc568431b446e2f209def2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webkernel/http',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/i18n' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => 'f773fc035cf4920bd58d7962a15e6ee31c44cca9',
            'type' => 'webkernel-stdlib',
            'install_path' => __DIR__ . '/../webkernel/i18n',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/imagery' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => 'ac501b9f3518b8abdee1c084ced2b5a3b506ef7a',
            'type' => 'webkernel-stdlib',
            'install_path' => __DIR__ . '/../webkernel/imagery',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/instance' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '6c6ae4ee5d41617509ef5f94fdbd2197c0addf55',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webkernel/instance',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/lifecycle' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '2bcfbf48c4f0723b3545ebe6f2030f522a683829',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../webkernel/lifecycle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/liveview' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '9f8ac0c8589b83ef9a38c42ad264fee30c12834a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webkernel/liveview',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/models' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => 'f5672f1c5ed5764d897d4ec3a9559582e50225e8',
            'type' => 'webkernel-stdlib',
            'install_path' => __DIR__ . '/../webkernel/models',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/notifications' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '53148c34c92ad769b8f7c7e1de1246a5a7261d69',
            'type' => 'webkernel-stdlib',
            'install_path' => __DIR__ . '/../webkernel/notifications',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/panels' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '5d3ad2400a42af80e202f03482de97457ceef161',
            'type' => 'webkernel-stdlib',
            'install_path' => __DIR__ . '/../webkernel/panels',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/paths' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '6cb6c9e2ffecae6354a93843f332a1c1067e820b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webkernel/paths',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/performance' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '156bbaa0716bf9ade042d4f16dbd5a3729b3449f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webkernel/performance',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/platform' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '4731c4d7f9f780dd4fd1861042a96dd717fbf162',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webkernel/platform',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/platform-provider' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '06902b583272d6186e913832f7e22776e0dd7071',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webkernel/platform-provider',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/request' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '0c5b40b70e4ab89f6b77835cd69b21edd49d2c86',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webkernel/request',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/route' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '801186d04ffe4745560e0fea82c985e235fdfddf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webkernel/route',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/schemas' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => 'de77e49846a607b84fb704f226f97e58e86fec5d',
            'type' => 'webkernel-stdlib',
            'install_path' => __DIR__ . '/../webkernel/schemas',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/system' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '2e32a483cf997442a95ab11c795da4043697c96c',
            'type' => 'webkernel-stdlib',
            'install_path' => __DIR__ . '/../webkernel/system',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/tables' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => 'bcbb1bb2956aeee6ee6b59744a631fcd0b3e392f',
            'type' => 'webkernel-stdlib',
            'install_path' => __DIR__ . '/../webkernel/tables',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/typography' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '30072fb7745c8796e24ba00afdd18c13889734aa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webkernel/typography',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/view' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '432420e3f6423a4df551a2ab0c13e0fd931da2f3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webkernel/view',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/webkernel' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '6d64e5d27e2969c8617b4928af57d1f794f6393b',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/widgets' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => 'bd1c475e1ce7a2ea6de844bbd84c99dd408e3dea',
            'type' => 'webkernel-stdlib',
            'install_path' => __DIR__ . '/../webkernel/widgets',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
