<?php return array(
    'root' => array(
        'name' => 'webkernel/webkernel',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '26ff356a145fab3a321d771b4e15dc9b9da93889',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        'composer/installers' => array(
            'pretty_version' => 'v2.3.0',
            'version' => '2.3.0.0',
            'reference' => '12fb2dfe5e16183de69e784a7b84046c43d97e8e',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./installers',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.12.0',
            'version' => '6.12.0.0',
            'reference' => 'd1ac35d784bf9f5e61b424901d5a014967f15b12',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'aa5030cfa5405eccfdcb1083ce040c2cb8d253bf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/clock' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'e41a24703d4560fd0acb709162f73b8adfc3aa0d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/clock',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'c71ecc56dfe541dbd90c5360474fbc405f8d5963',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => 'bb5906edc1c324c9a05aa0873d40117941e5fa90',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '2b4765fddfe3b508ac62f829e852b1501d3f6e8a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message' => array(
            'pretty_version' => '2.0',
            'version' => '2.0.0.0',
            'reference' => '402d35bcb92c70c026d1a6a9883f06b2ead23d71',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => 'f16e1d5863e37f8d8c2a01719f5b34baa2b714d3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '764e0b3939f5ca87cb904f570ef9be2d78a07865',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/codebase' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '37b40c6ac17bd523ffd93f2b657fb66e38481807',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webkernel/codebase',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/commands' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '44358bcfa16a816129f15d41829415a8d216e9d4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webkernel/commands',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/composables' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '58f2898b18d272225032b6e3e3d750a98677067a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webkernel/composables',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/config' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '8da19ca99edb61ed9d2118b2f59aae6b2f802445',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webkernel/config',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/console' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => 'c239e8bcc1b548cc020c44ec68249a044a9cac79',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webkernel/console',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/lifecycle' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '2bcfbf48c4f0723b3545ebe6f2030f522a683829',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../webkernel/lifecycle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/webkernel' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '26ff356a145fab3a321d771b4e15dc9b9da93889',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
