<?php declare(strict_types=1);
//> This file is part of Webkernel.
//> (c) 2025 - 2027 Numerimondes, El Moumen Yassine
//> Yassine El Moumen <yassine@numerimondes.com> | <platform@webkernelphp.com>
//> For the full copyright and license information, please view the LICENSE
//> file that was distributed with this source code.
namespace Webkernel\Lifecycle\Concerns\Builtin;

use Composer\Script\Event;
use Webkernel\Lifecycle\Concerns\Contracts\LifecycleConcernContract;

/**
 * Concern: Generate path helper functions.
 *
 * Emits a PHP file that exposes:
 *   platform_path(string $path = ''): string
 *   storage_path(string $path = ''): string
 *   base_path(string $path = ''): string
 *
 * Output: vendor/webkernel/path-helpers.php
 * The file is safe to re-generate on every dump-autoload (idempotent).
 */
final class GenPathHelpers implements LifecycleConcernContract
{
    public function name(): string
    {
        return 'Generate path helpers (platform_path, storage_path, base_path)';
    }

    public function handle(Event $event): void
    {
        $composer   = $event->getComposer();
        $vendor_dir = rtrim((string) $composer->getConfig()->get('vendor-dir'), '/\\');
        $base_dir   = \dirname($vendor_dir);

        $output_path = $vendor_dir . '/webkernel/path-helpers.php';
        $this->ensure_dir(\dirname($output_path));

        $content = $this->render($base_dir);
        \file_put_contents($output_path, $content);

        $event->getIO()->write(sprintf(
            '    <comment>Written: %s</comment>',
            $this->relative($output_path, $base_dir),
        ));
    }

    private function render(string $base_dir): string
    {
        $escaped = \addslashes($base_dir);

        return <<<PHP
        <?php declare(strict_types=1);
        //> Auto-generated by webkernel/lifecycle — do not edit.
        //> Re-generated on every `composer dump-autoload`.

        if (! function_exists('base_path')) {
            function base_path(string \$path = ''): string
            {
                \$base = '{$escaped}';
                return \$path !== '' ? \$base . DIRECTORY_SEPARATOR . ltrim(\$path, '/\\\\') : \$base;
            }
        }

        if (! function_exists('platform_path')) {
            function platform_path(string \$path = ''): string
            {
                return base_path(\$path);
            }
        }

        if (! function_exists('storage_path')) {
            function storage_path(string \$path = ''): string
            {
                \$storage = base_path('storage');
                return \$path !== '' ? \$storage . DIRECTORY_SEPARATOR . ltrim(\$path, '/\\\\') : \$storage;
            }
        }
        PHP;
    }

    private function ensure_dir(string $dir): void
    {
        if (! \is_dir($dir)) {
            \mkdir($dir, 0755, true);
        }
    }

    private function relative(string $path, string $base): string
    {
        return str_replace($base . '/', '', $path);
    }
}
