<?php declare(strict_types=1);
//> This file is part of Webkernel.
//> (c) 2025 - 2027 Numerimondes, El Moumen Yassine
//> Yassine El Moumen <yassine@numerimondes.com> | <platform@webkernelphp.com>
//> For the full copyright and license information, please view the LICENSE
//> file that was distributed with this source code.
namespace Webkernel\Lifecycle\Concerns\Builtin;

use Composer\Script\Event;
use Webkernel\Lifecycle\Concerns\Contracts\LifecycleConcernContract;

/**
 * Concern: Generate vendor helper functions.
 *
 * Emits a PHP file that exposes:
 *   vendor_path(string $path = ''): string
 *   autoload_path(): string
 *
 * Output: vendor/webkernel/vendor-helpers.php
 * The file is safe to re-generate on every dump-autoload (idempotent).
 */
final class GenVendorHelpers implements LifecycleConcernContract
{
    public function name(): string
    {
        return 'Generate vendor helpers (vendor_path, autoload_path)';
    }

    public function handle(Event $event): void
    {
        $composer   = $event->getComposer();
        $vendor_dir = rtrim((string) $composer->getConfig()->get('vendor-dir'), '/\\');
        $base_dir   = \dirname($vendor_dir);

        $output_path = $vendor_dir . '/webkernel/vendor-helpers.php';
        $this->ensure_dir(\dirname($output_path));

        $content = $this->render($vendor_dir);
        \file_put_contents($output_path, $content);

        $event->getIO()->write(sprintf(
            '    <comment>Written: %s</comment>',
            $this->relative($output_path, $base_dir),
        ));
    }

    private function render(string $vendor_dir): string
    {
        $escaped = \addslashes($vendor_dir);

        return <<<PHP
        <?php declare(strict_types=1);
        //> Auto-generated by webkernel/lifecycle — do not edit.
        //> Re-generated on every `composer dump-autoload`.

        if (! function_exists('vendor_path')) {
            function vendor_path(string \$path = ''): string
            {
                \$vendor = '{$escaped}';
                return \$path !== '' ? \$vendor . DIRECTORY_SEPARATOR . ltrim(\$path, '/\\\\') : \$vendor;
            }
        }

        if (! function_exists('autoload_path')) {
            function autoload_path(): string
            {
                return vendor_path('autoload.php');
            }
        }
        PHP;
    }

    private function ensure_dir(string $dir): void
    {
        if (! \is_dir($dir)) {
            \mkdir($dir, 0755, true);
        }
    }

    private function relative(string $path, string $base): string
    {
        return str_replace(\dirname($base) . '/', '', $path);
    }
}
