<?php declare(strict_types=1);
//> This file is part of Webkernel.
//> (c) 2025 - 2027 Numerimondes, El Moumen Yassine
//> Yassine El Moumen <yassine@numerimondes.com> | <platform@webkernelphp.com>
//> For the full copyright and license information, please view the LICENSE
//> file that was distributed with this source code.

return [
	'schema_version' => '1.0.1',

	'id'        => 'bf0b7a6fe1dc0f33e62c091b9c7fe6e9',
	'hostname'  => gethostname(),
	'ip'        => gethostbyname(\gethostname()),
	'uuid'      => Instance::machine_uuid(),
	'macs'      => Instance::macs(),
	'path'      => Instance::filepath(),
	'created'   => date('c'), // ISO timestamp

	'autoload'  => 'platform/dependencies/packagist/autoload.php', // Generated by platform/bootstrap/fast-boot.php. Do not edit.

	'platform' => [
		'id'             => 'bf0b7a6fe1dc0f33e62c091b9c7fe6e9',
		'path'           => 'platform',
		'config_path'    => __DIR__,
		'bootstrap_path' => 'platform/bootstrap',
		'cache_path'	 => 'platform/cache',
		'settings_path'  => 'platform/settings',
		'storage_path'   => 'platform/storage',
		'telemetry_path' => 'platform/telemetry',
		'temporary_path' => 'platform/temporary',
	],

	'dependencies' => [
		'path'              => 'platform/dependencies',
		'packagist_path'    => 'platform/dependencies/packagist',
		'node_modules_path' => 'platform/dependencies/node_modules',
		'package_json'      => 'platform/dependencies/package.json',
	],

	'modules' => [
		'path'          => 'modules',
		'manifest_path' => 'platform/cache/modules_manifest.php',
	],

	'public' => [
		'path'  => 'public',
		'index' => 'public/index.php',
	],

	'js' => [
		'manager'           => 'npm',
		'package_json'      => 'platform/dependencies/package.json',
		'node_modules_path' => 'platform/dependencies/node_modules',
	],

	'telemetry' => [
		'enabled'   => true,
		'logs_path' => 'platform/telemetry/logs',

		'structure' => [
			'logs' => [
				'access' => [
					'path'        => 'platform/telemetry/logs/access',
					'description' => 'High-throughput HTTP request/response logs',
				],
				'app' => [
					'path'        => 'platform/telemetry/logs/app',
					'description' => 'Application domain events and exceptions',
				],
				'system' => [
					'path'        => 'platform/telemetry/logs/system',
					'description' => 'Webkernel core lifecycle and low-level error logs',
				],
			],

			'metrics' => [
				'counters' => [
					'path'        => 'platform/telemetry/metrics/counters',
					'description' => 'Monotonically increasing values (total requests, error counts)',
				],
				'gauges' => [
					'path'        => 'platform/telemetry/metrics/gauges',
					'description' => 'Point-in-time metrics (memory usage, active workers)',
				],
				'histograms' => [
					'path'        => 'platform/telemetry/metrics/histograms',
					'description' => 'Statistical distributions (request latency, payload size)',
				],
			],

			'traces' => [
				'active' => [
					'path'        => 'platform/telemetry/traces/active',
					'description' => 'In-flight trace contexts and propagation headers',
				],
				'spans' => [
					'path'        => 'platform/telemetry/traces/spans',
					'description' => 'Completed span trees ready for collector export',
				],
			],

			'profiles' => [
				'cpu' => [
					'path'        => 'platform/telemetry/profiles/cpu',
					'description' => 'Execution clock sampling and call graphs',
				],
				'memory' => [
					'path'        => 'platform/telemetry/profiles/memory',
					'description' => 'Heap allocation snapshots and pointer tracking',
				],
			],

			'buffer' => [
				'shm' => [
					'path'        => 'platform/telemetry/buffer/shm',
					'description' => 'Shared memory segments (shmop, APCu, memory-mapped rings)',
				],
				'queue' => [
					'path'        => 'platform/telemetry/buffer/queue',
					'description' => 'Write-ahead log or disk-backed failover queues',
				],
			],
		],
	],
];
