<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));

return array(
    '0b24ec91e331da6d696dd874470799f3' => $vendorDir . '/webkernel/lifecycle/load.lifecycle.package-function.php',
    'e36e3041d2e2103dc3e9d57939707d6b' => $vendorDir . '/webkernel/codebase/load.codebase.package-function.php',
);
