<?php return array(
    'root' => array(
        'name' => 'webkernel/webkernel',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => null,
        'type' => 'project',
        'install_path' => __DIR__ . '/../../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'composer/installers' => array(
            'pretty_version' => 'v2.3.0',
            'version' => '2.3.0.0',
            'reference' => '12fb2dfe5e16183de69e784a7b84046c43d97e8e',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./installers',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'c71ecc56dfe541dbd90c5360474fbc405f8d5963',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/codebase' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '0798de1962213c73702b17b6ac92192193b2c8c2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webkernel/codebase',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/lifecycle' => array(
            'pretty_version' => '0.12.0',
            'version' => '0.12.0.0',
            'reference' => '3efccf4239d11474d3e37fd70d730eaa9a05c600',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../webkernel/lifecycle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webkernel/webkernel' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => null,
            'type' => 'project',
            'install_path' => __DIR__ . '/../../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
