<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));

return array(
    'Webkernel\\View\\' => array($vendorDir . '/webkernel/codebase/src/View/src'),
    'Webkernel\\Route\\' => array($vendorDir . '/webkernel/codebase/src/Route/src'),
    'Webkernel\\Platform\\' => array($vendorDir . '/webkernel/codebase/src/Platform/src'),
    'Webkernel\\Performance\\' => array($vendorDir . '/webkernel/codebase/src/Performance/src'),
    'Webkernel\\Paths\\' => array($vendorDir . '/webkernel/codebase/src/Paths/src'),
    'Webkernel\\Lifecycle\\' => array($vendorDir . '/webkernel/lifecycle/src/Lifecycle'),
    'Webkernel\\Instance\\' => array($vendorDir . '/webkernel/codebase/src/Instance/src'),
    'Webkernel\\Http\\' => array($vendorDir . '/webkernel/codebase/src/Http/src'),
    'Webkernel\\DevEnv\\' => array($vendorDir . '/webkernel/codebase/src/DevEnv/src'),
    'Webkernel\\Container\\' => array($vendorDir . '/webkernel/codebase/src/Container/src'),
    'Webkernel\\Console\\' => array($vendorDir . '/webkernel/codebase/src/Console/src'),
    'Webkernel\\Composables\\' => array($vendorDir . '/webkernel/codebase/src/Composables'),
    'Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'Composer\\Installers\\' => array($vendorDir . '/composer/installers/src/Composer/Installers'),
);
