<?php declare(strict_types=1);

//> This file is part of Webkernel.
//> (c) 2025 - 2027 Numerimondes, El Moumen Yassine
//> Yassine El Moumen <yassine@numerimondes.com> | <platform@webkernelphp.com>
//> For the full copyright and license information, please view the LICENSE
//> file that was distributed with this source code.
//>
//> Generated. Do not edit.

$v = dirname(__DIR__); // vendor_dir
$b = dirname($v); // base_dir

return array(
    'Webkernel\\Acl\\AuthorizationException' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Acl/src/AuthorizationException.php',
    'Webkernel\\Auth\\UserInterface' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Auth/src/UserInterface.php',
    'Webkernel\\Composables\\AclComposable' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Composables/AclComposable.php',
    'Webkernel\\Composables\\AuthComposable' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Composables/AuthComposable.php',
    'Webkernel\\Composables\\CacheComposable' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Composables/CacheComposable.php',
    'Webkernel\\Composables\\ClusterComposable' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Composables/ClusterComposable.php',
    'Webkernel\\Composables\\ComposableContract' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Composables/ComposableContract.php',
    'Webkernel\\Composables\\ConfigComposable' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Composables/ConfigComposable.php',
    'Webkernel\\Composables\\InstanceComposable' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Composables/InstanceComposable.php',
    'Webkernel\\Composables\\ModuleComposable' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Composables/ModuleComposable.php',
    'Webkernel\\Composables\\OwnersComposable' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Composables/OwnersComposable.php',
    'Webkernel\\Composables\\PageComposable' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Composables/PageComposable.php',
    'Webkernel\\Composables\\PanelComposable' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Composables/PanelComposable.php',
    'Webkernel\\Composables\\PlatformComposable' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Composables/PlatformComposable.php',
    'Webkernel\\Composables\\ResourceComposable' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Composables/ResourceComposable.php',
    'Webkernel\\Composables\\ResponseComposable' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Composables/ResponseComposable.php',
    'Webkernel\\Composables\\StorageComposable' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Composables/StorageComposable.php',
    'Webkernel\\Composables\\SystemAdminComposable' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Composables/SystemAdminComposable.php',
    'Webkernel\\Composables\\TelemetryComposable' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Composables/TelemetryComposable.php',
    'Webkernel\\Composables\\check' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Composables/check.php',
    'Webkernel\\Config\\ConfigWriter' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Config/src/ConfigWriter.php',
    'Webkernel\\Console\\Attribute\\ConsoleCommand' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Console/src/Attribute/ConsoleCommand.php',
    'Webkernel\\Console\\Cancelled' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Console/src/Cancelled.php',
    'Webkernel\\Console\\Commands\\DumpAutoloadCommand' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Console/src/Commands/DumpAutoloadCommand.php',
    'Webkernel\\Console\\Commands\\RoutesListCommand' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Console/src/Commands/RoutesListCommand.php',
    'Webkernel\\Console\\Commands\\ServerCommand' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Console/src/Commands/ServerCommand.php',
    'Webkernel\\Console\\ExitCode' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Console/src/ExitCode.php',
    'Webkernel\\Console\\Input\\ArgvInput' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Console/src/Input/ArgvInput.php',
    'Webkernel\\Console\\Kernel' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Console/src/Kernel.php',
    'Webkernel\\Console\\Middleware\\ConsoleMiddleware' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Console/src/Middleware/ConsoleMiddleware.php',
    'Webkernel\\Console\\Prompt' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Console/src/Prompt.php',
    'Webkernel\\Console\\Server\\Engine' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Console/src/Server/Engine.php',
    'Webkernel\\Console\\Server\\IncludeClock' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Console/src/Server/IncludeClock.php',
    'Webkernel\\Console\\Server\\router' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Console/src/Server/router.php',
    'Webkernel\\Console\\Terminal' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Console/src/Terminal.php',
    'Webkernel\\Container\\Container' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Container/src/Container.php',
    'Webkernel\\Container\\ContainerException' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Container/src/ContainerException.php',
    'Webkernel\\Container\\NotFound' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Container/src/NotFound.php',
    'Webkernel\\DevEnv\\IdeHelper' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/DevEnv/src/IdeHelper.php',
    'Webkernel\\Http\\Psr\\Response' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Http/src/Psr/Response.php',
    'Webkernel\\Http\\Psr\\ServerRequest' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Http/src/Psr/ServerRequest.php',
    'Webkernel\\Http\\Psr\\Stream' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Http/src/Psr/Stream.php',
    'Webkernel\\Http\\Psr\\UploadedFile' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Http/src/Psr/UploadedFile.php',
    'Webkernel\\Http\\Psr\\Uri' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Http/src/Psr/Uri.php',
    'Webkernel\\Http\\Request' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Http/src/Request.php',
    'Webkernel\\Instance\\InstanceId' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Instance/src/InstanceId.php',
    'Webkernel\\Lifecycle\\ComposerScripts' => $b . '/x-webkernel/lifecycle/src/Lifecycle/ComposerScripts.php',
    'Webkernel\\Lifecycle\\Installer\\LCBaseInstaller' => $b . '/x-webkernel/lifecycle/src/Lifecycle/Installer/LCBaseInstaller.php',
    'Webkernel\\Lifecycle\\Installer\\LCInstallerLocations' => $b . '/x-webkernel/lifecycle/src/Lifecycle/Installer/LCInstallerLocations.php',
    'Webkernel\\Lifecycle\\Installer\\LCPackageType' => $b . '/x-webkernel/lifecycle/src/Lifecycle/Installer/LCPackageType.php',
    'Webkernel\\Lifecycle\\LCInstaller' => $b . '/x-webkernel/lifecycle/src/Lifecycle/LCInstaller.php',
    'Webkernel\\Panel\\AdminPanel' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Panel/src/AdminPanel.php',
    'Webkernel\\Paths\\Composer' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Paths/src/Composer.php',
    'Webkernel\\Paths\\Package' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Paths/src/Package.php',
    'Webkernel\\Paths\\Path' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Paths/src/Path.php',
    'Webkernel\\Performance\\Actions\\EnableJitPerfAction' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Performance/src/Actions/EnableJitPerfAction.php',
    'Webkernel\\Performance\\Performance' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Performance/src/Performance.php',
    'Webkernel\\Performance\\Status' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Performance/src/Status.php',
    'Webkernel\\Platform\\AppOwner' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Platform/src/AppOwner.php',
    'Webkernel\\Platform\\Exceptions' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Platform/src/Exceptions.php',
    'Webkernel\\Platform\\Middleware' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Platform/src/Middleware.php',
    'Webkernel\\Platform\\Telemetry\\AccessLogWriter' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Platform/src/Telemetry/AccessLogWriter.php',
    'Webkernel\\Platform\\Telemetry\\MetricsCollector' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Platform/src/Telemetry/MetricsCollector.php',
    'Webkernel\\Platform\\Telemetry\\ProfileResult' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Platform/src/Telemetry/ProfileResult.php',
    'Webkernel\\Route\\Action\\RedirectAction' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Route/src/Action/RedirectAction.php',
    'Webkernel\\Route\\Action\\ViewAction' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Route/src/Action/ViewAction.php',
    'Webkernel\\Route\\Binding' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Route/src/Binding.php',
    'Webkernel\\Route\\Compile\\Cache' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Route/src/Compile/Cache.php',
    'Webkernel\\Route\\Compile\\Compiled' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Route/src/Compile/Compiled.php',
    'Webkernel\\Route\\Compile\\Generator' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Route/src/Compile/Generator.php',
    'Webkernel\\Route\\Compile\\Pattern' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Route/src/Compile/Pattern.php',
    'Webkernel\\Route\\Dispatch\\Dispatcher' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Route/src/Dispatch/Dispatcher.php',
    'Webkernel\\Route\\Dispatch\\Matched' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Route/src/Dispatch/Matched.php',
    'Webkernel\\Route\\Dispatch\\MethodNotAllowed' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Route/src/Dispatch/MethodNotAllowed.php',
    'Webkernel\\Route\\Dispatch\\NotMatched' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Route/src/Dispatch/NotMatched.php',
    'Webkernel\\Route\\Exception\\BadRoute' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Route/src/Exception/BadRoute.php',
    'Webkernel\\Route\\Group\\PendingGroup' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Route/src/Group/PendingGroup.php',
    'Webkernel\\Route\\Route' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Route/src/Route.php',
    'Webkernel\\Route\\RouteProvider' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Route/src/RouteProvider.php',
    'Webkernel\\Route\\Uri\\Uri' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Route/src/Uri/Uri.php',
    'Webkernel\\Route\\Uri\\UriException' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/Route/src/Uri/UriException.php',
    'Webkernel\\View\\Compiler' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/View/src/Compiler.php',
    'Webkernel\\View\\Engine' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/View/src/Engine.php',
    'Webkernel\\View\\Js' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/View/src/Js.php',
    'Webkernel\\View\\View' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/View/src/View.php',
    'Webkernel\\View\\ViewProvider' => '/home/yassine/Projects/framework/first_shot/x-webkernel/codebase/src/View/src/ViewProvider.php',
);
