#!/usr/bin/env php
<?php declare(strict_types=1);
//> This file is part of Webkernel.
//> (c) 2025 - 2027 Numerimondes, El Moumen Yassine
//> Yassine El Moumen <yassine@numerimondes.com> | <platform@webkernelphp.com>
//> For the full copyright and license information, please view the LICENSE
//> file that was distributed with this source code.

define('START_REQUEST', hrtime(true));

echo  'Binary is             :  ' . dirname(__DIR__) . $argv[0] . PHP_EOL
	. 'And first argument is :  ' . ($argv[1] ?? null);
