#!/usr/bin/env php
<?php declare(strict_types=1);

require __DIR__ . '/platform/dependencies/packagist/autoload.php';

use Webkernel\Container\Container;
use Webkernel\Cli\CliHandler;

$container = Container::get_instance();
$handler = new CliHandler($container);
$exit_code = $handler->handle($argv);
exit($exit_code);
