<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname(dirname($vendorDir)));

return array(
    'Webkernel\\Tests\\' => array($baseDir . '/x-webkernel/codebase/tests'),
    'Webkernel\\System\\Tests\\' => array($baseDir . '/x-webkernel/system/tests'),
    'Webkernel\\System\\' => array($vendorDir . '/webkernel/system/src'),
    'Webkernel\\Platform\\Tests\\' => array($baseDir . '/x-webkernel/platform/panels/tests'),
    'Webkernel\\Platform\\Schemas\\Tests\\' => array($baseDir . '/x-webkernel/platform/schemas/tests'),
    'Webkernel\\Platform\\Components\\Tests\\' => array($baseDir . '/x-webkernel/platform/components/tests'),
    'Webkernel\\Models\\Tests\\' => array($baseDir . '/x-webkernel/models/tests'),
    'Webkernel\\Lifecycle\\Tests\\' => array($baseDir . '/x-webkernel/lifecycle/tests'),
    'Webkernel\\Imagery\\Tests\\' => array($baseDir . '/x-webkernel/platform/imagery/tests'),
    'Webkernel\\I18n\\Tests\\' => array($baseDir . '/x-webkernel/platform/i18n/tests'),
    'Webkernel\\DevTools\\Tests\\' => array($baseDir . '/x-webkernel/devtools/tests'),
    'Webkernel\\DevTools\\' => array($vendorDir . '/webkernel/devtools/src'),
    'Webkernel\\Database\\Tests\\' => array($baseDir . '/x-webkernel/database/tests'),
    'Webkernel\\Database\\' => array($vendorDir . '/webkernel/database/src'),
    'Webkernel\\Auth\\Tests\\' => array($baseDir . '/x-webkernel/auth/tests'),
    'Webkernel\\' => array($vendorDir . '/webkernel/codebase/src'),
    'Psr\\SimpleCache\\' => array($vendorDir . '/psr/simple-cache/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/src'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
    'Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'Psr\\Clock\\' => array($vendorDir . '/psr/clock/src'),
    'Psr\\Cache\\' => array($vendorDir . '/psr/cache/src'),
    'PhpParser\\' => array($vendorDir . '/nikic/php-parser/lib/PhpParser'),
    'PHPMailer\\PHPMailer\\' => array($vendorDir . '/phpmailer/phpmailer/src'),
    'Modules\\' => array($baseDir . '/modules'),
    'DeepCopy\\' => array($vendorDir . '/myclabs/deep-copy/src/DeepCopy'),
    'Composer\\Installers\\' => array($vendorDir . '/composer/installers/src/Composer/Installers'),
);
