<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname(dirname($vendorDir)));

return array(
    'Webkernel\\System\\' => array($vendorDir . '/webkernel/system/src'),
    'Webkernel\\Platform\\Widgets\\' => array($vendorDir . '/webkernel/widgets/src'),
    'Webkernel\\Platform\\Tables\\' => array($vendorDir . '/webkernel/tables/src'),
    'Webkernel\\Platform\\Schemas\\' => array($vendorDir . '/webkernel/schemas/src'),
    'Webkernel\\Platform\\Notifications\\' => array($vendorDir . '/webkernel/notifications/src'),
    'Webkernel\\Platform\\Forms\\' => array($vendorDir . '/webkernel/forms/src'),
    'Webkernel\\Platform\\Components\\' => array($vendorDir . '/webkernel/components/src'),
    'Webkernel\\Platform\\Actions\\' => array($vendorDir . '/webkernel/actions/src'),
    'Webkernel\\Platform\\' => array($vendorDir . '/webkernel/panels/src'),
    'Webkernel\\Models\\' => array($vendorDir . '/webkernel/models/src'),
    'Webkernel\\Lifecycle\\' => array($vendorDir . '/webkernel/lifecycle/Lifecycle'),
    'Webkernel\\Imagery\\' => array($vendorDir . '/webkernel/imagery/src'),
    'Webkernel\\I18n\\' => array($vendorDir . '/webkernel/i18n/src'),
    'Webkernel\\DevTools\\' => array($vendorDir . '/webkernel/devtools/src'),
    'Webkernel\\Database\\' => array($vendorDir . '/webkernel/database/src'),
    'Webkernel\\Auth\\' => array($vendorDir . '/webkernel/auth/src'),
    'Webkernel\\' => array($vendorDir . '/webkernel/codebase/src'),
    'Psr\\SimpleCache\\' => array($vendorDir . '/psr/simple-cache/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/src'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
    'Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'Psr\\Clock\\' => array($vendorDir . '/psr/clock/src'),
    'Psr\\Cache\\' => array($vendorDir . '/psr/cache/src'),
    'PhpParser\\' => array($vendorDir . '/nikic/php-parser/lib/PhpParser'),
    'PHPMailer\\PHPMailer\\' => array($vendorDir . '/phpmailer/phpmailer/src'),
    'DeepCopy\\' => array($vendorDir . '/myclabs/deep-copy/src/DeepCopy'),
    'Composer\\Installers\\' => array($vendorDir . '/composer/installers/src/Composer/Installers'),
    'Acme\\Billing\\' => array($baseDir . '/modules/acme/billing/src'),
);
