<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitcc6f492cc5d64cb7f09b9024726d6929
{
    public static $files = array (
        'b3937b7fa35431fe0895577483870c74' => __DIR__ . '/..' . '/webkernel/codebase/namespacer.php',
    );

    public static $prefixLengthsPsr4 = array (
        'W' =>
        array (
            'Webkernel\\Lifecycle\\' => 20,
            'Webkernel\\' => 10,
        ),
        'P' =>
        array (
            'Psr\\SimpleCache\\' => 16,
            'Psr\\Log\\' => 8,
            'Psr\\Http\\Message\\' => 17,
            'Psr\\Http\\Client\\' => 16,
            'Psr\\Container\\' => 14,
            'Psr\\Clock\\' => 10,
            'Psr\\Cache\\' => 10,
        ),
        'M' =>
        array (
            'Modules\\' => 8,
        ),
        'C' =>
        array (
            'Composer\\Installers\\' => 20,
        ),
        'A' =>
        array (
            'Acme\\Billing\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Webkernel\\Lifecycle\\' =>
        array (
            0 => __DIR__ . '/..' . '/webkernel/lifecycle/Lifecycle',
        ),
        'Webkernel\\' =>
        array (
            0 => __DIR__ . '/..' . '/webkernel/codebase/src',
        ),
        'Psr\\SimpleCache\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/simple-cache/src',
        ),
        'Psr\\Log\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/log/src',
        ),
        'Psr\\Http\\Message\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/http-factory/src',
            1 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'Psr\\Http\\Client\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/http-client/src',
        ),
        'Psr\\Container\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
        'Psr\\Clock\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/clock/src',
        ),
        'Psr\\Cache\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/cache/src',
        ),
        'Modules\\' =>
        array (
            0 => __DIR__ . '/../../../..' . '/modules',
        ),
        'Composer\\Installers\\' =>
        array (
            0 => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers',
        ),
        'Acme\\Billing\\' =>
        array (
            0 => __DIR__ . '/../../../..' . '/modules/acme/billing/src',
        ),
    );

    public static $classMap = array (
        'Acme\\Billing\\BillingProvider' => __DIR__ . '/../../../..' . '/modules/acme/billing/src/BillingProvider.php',
        'Acme\\Billing\\Domain\\Invoice' => __DIR__ . '/../../../..' . '/modules/acme/billing/src/Domain/Invoice.php',
        'Acme\\Billing\\Infrastructure\\InvoiceStore' => __DIR__ . '/../../../..' . '/modules/acme/billing/src/Infrastructure/InvoiceStore.php',
        'Acme\\Billing\\Presentation\\BillingPanelProvider' => __DIR__ . '/../../../..' . '/modules/acme/billing/src/Presentation/BillingPanelProvider.php',
        'Acme\\Billing\\Presentation\\Resources\\Invoices\\InvoiceResource' => __DIR__ . '/../../../..' . '/modules/acme/billing/src/Presentation/Resources/Invoices/InvoiceResource.php',
        'Acme\\Billing\\Presentation\\Resources\\Invoices\\Pages\\CreateInvoice' => __DIR__ . '/../../../..' . '/modules/acme/billing/src/Presentation/Resources/Invoices/Pages/CreateInvoice.php',
        'Acme\\Billing\\Presentation\\Resources\\Invoices\\Pages\\EditInvoice' => __DIR__ . '/../../../..' . '/modules/acme/billing/src/Presentation/Resources/Invoices/Pages/EditInvoice.php',
        'Acme\\Billing\\Presentation\\Resources\\Invoices\\Pages\\ListInvoices' => __DIR__ . '/../../../..' . '/modules/acme/billing/src/Presentation/Resources/Invoices/Pages/ListInvoices.php',
        'Acme\\Billing\\Presentation\\Resources\\Invoices\\Schemas\\InvoiceForm' => __DIR__ . '/../../../..' . '/modules/acme/billing/src/Presentation/Resources/Invoices/Schemas/InvoiceForm.php',
        'Acme\\Billing\\Presentation\\Resources\\Invoices\\Tables\\InvoicesTable' => __DIR__ . '/../../../..' . '/modules/acme/billing/src/Presentation/Resources/Invoices/Tables/InvoicesTable.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Composer\\Installers\\AglInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/AglInstaller.php',
        'Composer\\Installers\\AkauntingInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/AkauntingInstaller.php',
        'Composer\\Installers\\AnnotateCmsInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/AnnotateCmsInstaller.php',
        'Composer\\Installers\\AsgardInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/AsgardInstaller.php',
        'Composer\\Installers\\AttogramInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/AttogramInstaller.php',
        'Composer\\Installers\\BaseInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/BaseInstaller.php',
        'Composer\\Installers\\BitrixInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/BitrixInstaller.php',
        'Composer\\Installers\\BonefishInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/BonefishInstaller.php',
        'Composer\\Installers\\BotbleInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/BotbleInstaller.php',
        'Composer\\Installers\\CakePHPInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/CakePHPInstaller.php',
        'Composer\\Installers\\ChefInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/ChefInstaller.php',
        'Composer\\Installers\\CiviCrmInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/CiviCrmInstaller.php',
        'Composer\\Installers\\ClanCatsFrameworkInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/ClanCatsFrameworkInstaller.php',
        'Composer\\Installers\\CockpitInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/CockpitInstaller.php',
        'Composer\\Installers\\CodeIgniterInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/CodeIgniterInstaller.php',
        'Composer\\Installers\\Concrete5Installer' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/Concrete5Installer.php',
        'Composer\\Installers\\ConcreteCMSInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/ConcreteCMSInstaller.php',
        'Composer\\Installers\\CroogoInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/CroogoInstaller.php',
        'Composer\\Installers\\DecibelInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/DecibelInstaller.php',
        'Composer\\Installers\\DframeInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/DframeInstaller.php',
        'Composer\\Installers\\DokuWikiInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/DokuWikiInstaller.php',
        'Composer\\Installers\\DolibarrInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/DolibarrInstaller.php',
        'Composer\\Installers\\DrupalInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/DrupalInstaller.php',
        'Composer\\Installers\\ElggInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/ElggInstaller.php',
        'Composer\\Installers\\EliasisInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/EliasisInstaller.php',
        'Composer\\Installers\\ExpressionEngineInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/ExpressionEngineInstaller.php',
        'Composer\\Installers\\EzPlatformInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/EzPlatformInstaller.php',
        'Composer\\Installers\\ForkCMSInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/ForkCMSInstaller.php',
        'Composer\\Installers\\FuelInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/FuelInstaller.php',
        'Composer\\Installers\\FuelphpInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/FuelphpInstaller.php',
        'Composer\\Installers\\GravInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/GravInstaller.php',
        'Composer\\Installers\\HuradInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/HuradInstaller.php',
        'Composer\\Installers\\ImageCMSInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/ImageCMSInstaller.php',
        'Composer\\Installers\\Installer' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/Installer.php',
        'Composer\\Installers\\ItopInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/ItopInstaller.php',
        'Composer\\Installers\\KanboardInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/KanboardInstaller.php',
        'Composer\\Installers\\KnownInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/KnownInstaller.php',
        'Composer\\Installers\\KodiCMSInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/KodiCMSInstaller.php',
        'Composer\\Installers\\KohanaInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/KohanaInstaller.php',
        'Composer\\Installers\\LanManagementSystemInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/LanManagementSystemInstaller.php',
        'Composer\\Installers\\LaravelInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/LaravelInstaller.php',
        'Composer\\Installers\\LavaLiteInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/LavaLiteInstaller.php',
        'Composer\\Installers\\LithiumInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/LithiumInstaller.php',
        'Composer\\Installers\\MODULEWorkInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/MODULEWorkInstaller.php',
        'Composer\\Installers\\MODXEvoInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/MODXEvoInstaller.php',
        'Composer\\Installers\\MagentoInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/MagentoInstaller.php',
        'Composer\\Installers\\MajimaInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/MajimaInstaller.php',
        'Composer\\Installers\\MakoInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/MakoInstaller.php',
        'Composer\\Installers\\MantisBTInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/MantisBTInstaller.php',
        'Composer\\Installers\\MatomoInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/MatomoInstaller.php',
        'Composer\\Installers\\MauticInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/MauticInstaller.php',
        'Composer\\Installers\\MayaInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/MayaInstaller.php',
        'Composer\\Installers\\MediaWikiInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/MediaWikiInstaller.php',
        'Composer\\Installers\\MiaoxingInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/MiaoxingInstaller.php',
        'Composer\\Installers\\MicroweberInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/MicroweberInstaller.php',
        'Composer\\Installers\\ModxInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/ModxInstaller.php',
        'Composer\\Installers\\MoodleInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/MoodleInstaller.php',
        'Composer\\Installers\\OctoberInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/OctoberInstaller.php',
        'Composer\\Installers\\OntoWikiInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/OntoWikiInstaller.php',
        'Composer\\Installers\\OsclassInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/OsclassInstaller.php',
        'Composer\\Installers\\OxidInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/OxidInstaller.php',
        'Composer\\Installers\\PPIInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/PPIInstaller.php',
        'Composer\\Installers\\PantheonInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/PantheonInstaller.php',
        'Composer\\Installers\\PhiftyInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/PhiftyInstaller.php',
        'Composer\\Installers\\PhpBBInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/PhpBBInstaller.php',
        'Composer\\Installers\\PiwikInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/PiwikInstaller.php',
        'Composer\\Installers\\PlentymarketsInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/PlentymarketsInstaller.php',
        'Composer\\Installers\\Plugin' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/Plugin.php',
        'Composer\\Installers\\PortoInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/PortoInstaller.php',
        'Composer\\Installers\\PrestashopInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/PrestashopInstaller.php',
        'Composer\\Installers\\ProcessWireInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/ProcessWireInstaller.php',
        'Composer\\Installers\\PuppetInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/PuppetInstaller.php',
        'Composer\\Installers\\PxcmsInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/PxcmsInstaller.php',
        'Composer\\Installers\\RadPHPInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/RadPHPInstaller.php',
        'Composer\\Installers\\ReIndexInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/ReIndexInstaller.php',
        'Composer\\Installers\\Redaxo5Installer' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/Redaxo5Installer.php',
        'Composer\\Installers\\RedaxoInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/RedaxoInstaller.php',
        'Composer\\Installers\\RoundcubeInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/RoundcubeInstaller.php',
        'Composer\\Installers\\SMFInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/SMFInstaller.php',
        'Composer\\Installers\\ShopwareInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/ShopwareInstaller.php',
        'Composer\\Installers\\SilverStripeInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/SilverStripeInstaller.php',
        'Composer\\Installers\\SiteDirectInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/SiteDirectInstaller.php',
        'Composer\\Installers\\StarbugInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/StarbugInstaller.php',
        'Composer\\Installers\\SyDESInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/SyDESInstaller.php',
        'Composer\\Installers\\SyliusInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/SyliusInstaller.php',
        'Composer\\Installers\\TaoInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/TaoInstaller.php',
        'Composer\\Installers\\TastyIgniterInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/TastyIgniterInstaller.php',
        'Composer\\Installers\\TheliaInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/TheliaInstaller.php',
        'Composer\\Installers\\TuskInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/TuskInstaller.php',
        'Composer\\Installers\\UserFrostingInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/UserFrostingInstaller.php',
        'Composer\\Installers\\VanillaInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/VanillaInstaller.php',
        'Composer\\Installers\\VgmcpInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/VgmcpInstaller.php',
        'Composer\\Installers\\WHMCSInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/WHMCSInstaller.php',
        'Composer\\Installers\\WinterInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/WinterInstaller.php',
        'Composer\\Installers\\WolfCMSInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/WolfCMSInstaller.php',
        'Composer\\Installers\\WordPressInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/WordPressInstaller.php',
        'Composer\\Installers\\YawikInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/YawikInstaller.php',
        'Composer\\Installers\\ZendInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/ZendInstaller.php',
        'Composer\\Installers\\ZikulaInstaller' => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers/ZikulaInstaller.php',
        'Psr\\Cache\\CacheException' => __DIR__ . '/..' . '/psr/cache/src/CacheException.php',
        'Psr\\Cache\\CacheItemInterface' => __DIR__ . '/..' . '/psr/cache/src/CacheItemInterface.php',
        'Psr\\Cache\\CacheItemPoolInterface' => __DIR__ . '/..' . '/psr/cache/src/CacheItemPoolInterface.php',
        'Psr\\Cache\\InvalidArgumentException' => __DIR__ . '/..' . '/psr/cache/src/InvalidArgumentException.php',
        'Psr\\Clock\\ClockInterface' => __DIR__ . '/..' . '/psr/clock/src/ClockInterface.php',
        'Psr\\Container\\ContainerExceptionInterface' => __DIR__ . '/..' . '/psr/container/src/ContainerExceptionInterface.php',
        'Psr\\Container\\ContainerInterface' => __DIR__ . '/..' . '/psr/container/src/ContainerInterface.php',
        'Psr\\Container\\NotFoundExceptionInterface' => __DIR__ . '/..' . '/psr/container/src/NotFoundExceptionInterface.php',
        'Psr\\Http\\Client\\ClientExceptionInterface' => __DIR__ . '/..' . '/psr/http-client/src/ClientExceptionInterface.php',
        'Psr\\Http\\Client\\ClientInterface' => __DIR__ . '/..' . '/psr/http-client/src/ClientInterface.php',
        'Psr\\Http\\Client\\NetworkExceptionInterface' => __DIR__ . '/..' . '/psr/http-client/src/NetworkExceptionInterface.php',
        'Psr\\Http\\Client\\RequestExceptionInterface' => __DIR__ . '/..' . '/psr/http-client/src/RequestExceptionInterface.php',
        'Psr\\Http\\Message\\MessageInterface' => __DIR__ . '/..' . '/psr/http-message/src/MessageInterface.php',
        'Psr\\Http\\Message\\RequestFactoryInterface' => __DIR__ . '/..' . '/psr/http-factory/src/RequestFactoryInterface.php',
        'Psr\\Http\\Message\\RequestInterface' => __DIR__ . '/..' . '/psr/http-message/src/RequestInterface.php',
        'Psr\\Http\\Message\\ResponseFactoryInterface' => __DIR__ . '/..' . '/psr/http-factory/src/ResponseFactoryInterface.php',
        'Psr\\Http\\Message\\ResponseInterface' => __DIR__ . '/..' . '/psr/http-message/src/ResponseInterface.php',
        'Psr\\Http\\Message\\ServerRequestFactoryInterface' => __DIR__ . '/..' . '/psr/http-factory/src/ServerRequestFactoryInterface.php',
        'Psr\\Http\\Message\\ServerRequestInterface' => __DIR__ . '/..' . '/psr/http-message/src/ServerRequestInterface.php',
        'Psr\\Http\\Message\\StreamFactoryInterface' => __DIR__ . '/..' . '/psr/http-factory/src/StreamFactoryInterface.php',
        'Psr\\Http\\Message\\StreamInterface' => __DIR__ . '/..' . '/psr/http-message/src/StreamInterface.php',
        'Psr\\Http\\Message\\UploadedFileFactoryInterface' => __DIR__ . '/..' . '/psr/http-factory/src/UploadedFileFactoryInterface.php',
        'Psr\\Http\\Message\\UploadedFileInterface' => __DIR__ . '/..' . '/psr/http-message/src/UploadedFileInterface.php',
        'Psr\\Http\\Message\\UriFactoryInterface' => __DIR__ . '/..' . '/psr/http-factory/src/UriFactoryInterface.php',
        'Psr\\Http\\Message\\UriInterface' => __DIR__ . '/..' . '/psr/http-message/src/UriInterface.php',
        'Psr\\Log\\AbstractLogger' => __DIR__ . '/..' . '/psr/log/src/AbstractLogger.php',
        'Psr\\Log\\InvalidArgumentException' => __DIR__ . '/..' . '/psr/log/src/InvalidArgumentException.php',
        'Psr\\Log\\LogLevel' => __DIR__ . '/..' . '/psr/log/src/LogLevel.php',
        'Psr\\Log\\LoggerAwareInterface' => __DIR__ . '/..' . '/psr/log/src/LoggerAwareInterface.php',
        'Psr\\Log\\LoggerAwareTrait' => __DIR__ . '/..' . '/psr/log/src/LoggerAwareTrait.php',
        'Psr\\Log\\LoggerInterface' => __DIR__ . '/..' . '/psr/log/src/LoggerInterface.php',
        'Psr\\Log\\LoggerTrait' => __DIR__ . '/..' . '/psr/log/src/LoggerTrait.php',
        'Psr\\Log\\NullLogger' => __DIR__ . '/..' . '/psr/log/src/NullLogger.php',
        'Psr\\SimpleCache\\CacheException' => __DIR__ . '/..' . '/psr/simple-cache/src/CacheException.php',
        'Psr\\SimpleCache\\CacheInterface' => __DIR__ . '/..' . '/psr/simple-cache/src/CacheInterface.php',
        'Psr\\SimpleCache\\InvalidArgumentException' => __DIR__ . '/..' . '/psr/simple-cache/src/InvalidArgumentException.php',
        'Webkernel\\CodebaseProvider' => __DIR__ . '/..' . '/webkernel/codebase/src/CodebaseProvider.php',
        'Webkernel\\Composables\\ComposableContract' => __DIR__ . '/..' . '/webkernel/codebase/src/Composables/ComposableContract.php',
        'Webkernel\\Composables\\ConfigComposable' => __DIR__ . '/..' . '/webkernel/codebase/src/Composables/ConfigComposable.php',
        'Webkernel\\Composables\\PanelComposable' => __DIR__ . '/..' . '/webkernel/codebase/src/Composables/PanelComposable.php',
        'Webkernel\\Config\\Config' => __DIR__ . '/..' . '/webkernel/codebase/src/Config/Config.php',
        'Webkernel\\Config\\ConfigWriter' => __DIR__ . '/..' . '/webkernel/codebase/src/Config/ConfigWriter.php',
        'Webkernel\\Console' => __DIR__ . '/..' . '/webkernel/codebase/src/Console.php',
        'Webkernel\\Console\\Attribute\\ConsoleCommand' => __DIR__ . '/..' . '/webkernel/codebase/src/Console/Attribute/ConsoleCommand.php',
        'Webkernel\\Console\\Cancelled' => __DIR__ . '/..' . '/webkernel/codebase/src/Console/Cancelled.php',
        'Webkernel\\Console\\Commands\\DumpAutoloadCommand' => __DIR__ . '/..' . '/webkernel/codebase/src/Console/Commands/DumpAutoloadCommand.php',
        'Webkernel\\Console\\ExitCode' => __DIR__ . '/..' . '/webkernel/codebase/src/Console/ExitCode.php',
        'Webkernel\\Console\\Input\\ArgvInput' => __DIR__ . '/..' . '/webkernel/codebase/src/Console/Input/ArgvInput.php',
        'Webkernel\\Console\\Kernel' => __DIR__ . '/..' . '/webkernel/codebase/src/Console/Kernel.php',
        'Webkernel\\Console\\Middleware\\ConsoleMiddleware' => __DIR__ . '/..' . '/webkernel/codebase/src/Console/Middleware/ConsoleMiddleware.php',
        'Webkernel\\Console\\Prompt' => __DIR__ . '/..' . '/webkernel/codebase/src/Console/Prompt.php',
        'Webkernel\\Console\\Terminal' => __DIR__ . '/..' . '/webkernel/codebase/src/Console/Terminal.php',
        'Webkernel\\DevEnv\\IdeHelper' => __DIR__ . '/..' . '/webkernel/codebase/src/DevEnv/IdeHelper.php',
        'Webkernel\\Http' => __DIR__ . '/..' . '/webkernel/codebase/src/Http.php',
        'Webkernel\\Instance\\InstanceId' => __DIR__ . '/..' . '/webkernel/codebase/src/Instance/InstanceId.php',
        'Webkernel\\Lifecycle\\ComposerScripts' => __DIR__ . '/..' . '/webkernel/lifecycle/Lifecycle/ComposerScripts.php',
        'Webkernel\\Lifecycle\\Installer\\LCBaseInstaller' => __DIR__ . '/..' . '/webkernel/lifecycle/Lifecycle/Installer/LCBaseInstaller.php',
        'Webkernel\\Lifecycle\\Installer\\LCInstallerLocations' => __DIR__ . '/..' . '/webkernel/lifecycle/Lifecycle/Installer/LCInstallerLocations.php',
        'Webkernel\\Lifecycle\\Installer\\LCPackageType' => __DIR__ . '/..' . '/webkernel/lifecycle/Lifecycle/Installer/LCPackageType.php',
        'Webkernel\\Lifecycle\\LCInstaller' => __DIR__ . '/..' . '/webkernel/lifecycle/Lifecycle/LCInstaller.php',
        'Webkernel\\Paths\\Package' => __DIR__ . '/..' . '/webkernel/codebase/src/Paths/Package.php',
        'Webkernel\\PlatformProvider' => __DIR__ . '/..' . '/webkernel/codebase/src/PlatformProvider.php',
        'Webkernel\\Platform\\Colors\\Color' => __DIR__ . '/..' . '/webkernel/codebase/src/Platform/Colors/Color.php',
        'Webkernel\\Platform\\Http\\Middleware\\Authenticate' => __DIR__ . '/..' . '/webkernel/codebase/src/Platform/Http/Middleware/Authenticate.php',
        'Webkernel\\Platform\\Pages\\Dashboard' => __DIR__ . '/..' . '/webkernel/codebase/src/Platform/Pages/Dashboard.php',
        'Webkernel\\Platform\\Panel' => __DIR__ . '/..' . '/webkernel/codebase/src/Platform/Panel.php',
        'Webkernel\\Platform\\PanelProvider' => __DIR__ . '/..' . '/webkernel/codebase/src/Platform/PanelProvider.php',
        'Webkernel\\Platform\\Resources\\Resource' => __DIR__ . '/..' . '/webkernel/codebase/src/Platform/Resources/Resource.php',
        'Webkernel\\Platform\\Schemas\\Schema' => __DIR__ . '/..' . '/webkernel/codebase/src/Platform/Schemas/Schema.php',
        'Webkernel\\Platform\\System\\SystemPanelProvider' => __DIR__ . '/..' . '/webkernel/codebase/src/Platform/System/SystemPanelProvider.php',
        'Webkernel\\Platform\\Tables\\Table' => __DIR__ . '/..' . '/webkernel/codebase/src/Platform/Tables/Table.php',
        'Webkernel\\Route\\Action\\RedirectAction' => __DIR__ . '/..' . '/webkernel/codebase/src/Route/Action/RedirectAction.php',
        'Webkernel\\Route\\Action\\ViewAction' => __DIR__ . '/..' . '/webkernel/codebase/src/Route/Action/ViewAction.php',
        'Webkernel\\Route\\Binding' => __DIR__ . '/..' . '/webkernel/codebase/src/Route/Binding.php',
        'Webkernel\\Route\\Compile\\Cache' => __DIR__ . '/..' . '/webkernel/codebase/src/Route/Compile/Cache.php',
        'Webkernel\\Route\\Compile\\Compiled' => __DIR__ . '/..' . '/webkernel/codebase/src/Route/Compile/Compiled.php',
        'Webkernel\\Route\\Compile\\Generator' => __DIR__ . '/..' . '/webkernel/codebase/src/Route/Compile/Generator.php',
        'Webkernel\\Route\\Compile\\Pattern' => __DIR__ . '/..' . '/webkernel/codebase/src/Route/Compile/Pattern.php',
        'Webkernel\\Route\\Dispatch\\Dispatcher' => __DIR__ . '/..' . '/webkernel/codebase/src/Route/Dispatch/Dispatcher.php',
        'Webkernel\\Route\\Dispatch\\Matched' => __DIR__ . '/..' . '/webkernel/codebase/src/Route/Dispatch/Matched.php',
        'Webkernel\\Route\\Dispatch\\MethodNotAllowed' => __DIR__ . '/..' . '/webkernel/codebase/src/Route/Dispatch/MethodNotAllowed.php',
        'Webkernel\\Route\\Dispatch\\NotMatched' => __DIR__ . '/..' . '/webkernel/codebase/src/Route/Dispatch/NotMatched.php',
        'Webkernel\\Route\\Exception\\BadRoute' => __DIR__ . '/..' . '/webkernel/codebase/src/Route/Exception/BadRoute.php',
        'Webkernel\\Route\\Group\\PendingGroup' => __DIR__ . '/..' . '/webkernel/codebase/src/Route/Group/PendingGroup.php',
        'Webkernel\\Route\\Route' => __DIR__ . '/..' . '/webkernel/codebase/src/Route/Route.php',
        'Webkernel\\Route\\Uri\\Uri' => __DIR__ . '/..' . '/webkernel/codebase/src/Route/Uri/Uri.php',
        'Webkernel\\Route\\Uri\\UriException' => __DIR__ . '/..' . '/webkernel/codebase/src/Route/Uri/UriException.php',
        'Webkernel\\View\\Compiler' => __DIR__ . '/..' . '/webkernel/codebase/src/View/Compiler.php',
        'Webkernel\\View\\Engine' => __DIR__ . '/..' . '/webkernel/codebase/src/View/Engine.php',
        'Webkernel\\View\\Js' => __DIR__ . '/..' . '/webkernel/codebase/src/View/Js.php',
        'Webkernel\\View\\View' => __DIR__ . '/..' . '/webkernel/codebase/src/View/View.php',
        'Webkernel\\WebApp' => __DIR__ . '/..' . '/webkernel/codebase/src/WebApp.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitcc6f492cc5d64cb7f09b9024726d6929::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitcc6f492cc5d64cb7f09b9024726d6929::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitcc6f492cc5d64cb7f09b9024726d6929::$classMap;

        }, null, ClassLoader::class);
    }
}
